### ISSUE TITLE
jGrowl option

### ISSUE THREAD

**Issue by ezersky** [bezumkin/AjaxForm#14]
Add an option in Manager to enable/disable jGrowl for ajaxForm please

Or how to disable jGrowl manually?

**Comment by bezumkin** [comment]
1. Copy [default.js](https://github.com/bezumkin/AjaxForm/blob/master/assets/components/ajaxform/js/default.js) to custom.js.
2. Change [AjaxForm.Message](https://github.com/bezumkin/AjaxForm/blob/master/assets/components/ajaxform/js/default.js#L79-L101) functions in new file.
3. Specify new file in &frontend_js:
```
[[!AjaxForm?
    &frontend_js=`[[+assetsUrl]]js/custom.js`
]]
```
