### ISSUE TITLE
Прикрепление файлов

### ISSUE THREAD

**Issue by sin4end** [bezumkin/AjaxForm#16]
Василий, получился очень крутой и универсальный компонент. Но пожалуйста, не мог бы ты сделать функционал отправки файла? Он предусмотрен jQuery-плагином, но я так предполагаю, что не работает в твоём компоненте из-за этой строчки: https://github.com/bezumkin/AjaxForm/blob/master/assets/components/ajaxform/js/default.js#L17 , так как картинку в json передать весьма.. Затруднительно.

Спасибо!

**Comment by bezumkin** [comment]
http://malsup.com/jquery/form/#json
> **dataType** identifies the expected content type of the **server response**

Отправка файлов работает без проблем, только что проверил
[![](https://file.modx.pro/files/8/a/1/8a16b3e228d6185bca903b6008bdda8es.jpg)](https://file.modx.pro/files/8/a/1/8a16b3e228d6185bca903b6008bdda8e.png)
