### ISSUE TITLE
FormItSaveForm as a hook for AjaxForm fails due to empty resource

### ISSUE THREAD

**Issue by PatchRanger** [bezumkin/AjaxForm#18]
## How to reproduce
1) Place `AjaxForm` snippet with `FormItSaveForm` hook:
```
[[!AjaxForm?
    &form=`myForm`
    &hooks=`FormItSaveForm`
]]
```
2) Try to save the form.

## Expected result
Form successfully submitted and saved via `FormItSaveForm`.

## Real result
Submission fails with such error:
``
Fatal error: Call to a member function get() on null
``
It refers to cache file and is related to that line: https://github.com/modxcms/FormIt/blob/develop/core/components/formit/elements/snippets/snippet.formitsaveform.php#L35 .

## Reason
The reason is obviously in the fact that no resource is assigned.

## Solution
Set resource during handling request in `action.php`. I am going to provide a pull-request soon.

**Comment by bezumkin** [comment]
Do you have the latest version installed?

I already [fixed it](https://github.com/bezumkin/AjaxForm/commit/9625a20caeb15d821a57bc42c27d08cdfe91cd32).

**Comment by PatchRanger** [comment]
Ah, thank you for pointing to this. I have the latest from modx repo. I should update to the latest possible. Thank you for fixing as well.

**Comment by bezumkin** [comment]
Sorry, I forgot to update package in MODX repo.

Updated just now.

**Comment by PatchRanger** [comment]
That's great, thank you, Vasily.
