### ISSUE TITLE
AjaxForm memory leak

### ISSUE THREAD

**Issue by bschwenk** [bezumkin/AjaxForm#20]
* MODX Revolution 2.3.3-pl (traditional)
* FormIt 2.2.6-pl
* AjaxForm 1.1.1-pl

With the below form and AjaxForm call, I get a fatal memory error from PHP.

![image](https://cloud.githubusercontent.com/assets/8420188/8322445/22f6db66-1a03-11e5-9512-443e019e4636.png)

After refreshing, I get a similar error but with a different file:

![image](https://cloud.githubusercontent.com/assets/8420188/8322456/57fe1432-1a03-11e5-8e32-0248eb8aa9cb.png)

Code below:

```html
<form method="post" id="inquiry-form" class="ajax_form" action="[[~[[*id]]]]#inquiry-form">

  [[!+fi.validationErrorMessage:notempty=`<p id="if-main-error">[[!+fi.validationErrorMessage]]</p>`]]
  [[!+fi.successMessage:notempty=`<p id="if-success">[[!+fi.successMessage]]</p>`]]

  <div>
    <label for="if-name">Your name:</label><span class="if-error">[[!+fi.error.if-name]]</span>
    <input type="text" id="if-name" name="if-name" />
  </div>
  <div>
    <label for="if-email">E-mail:</label><span class="if-error">[[!+fi.error.if-email]]</span>
    <input type="email" id="if-email" name="if-email"/>
  </div>
  <div>
    <label for="if-phone">Phone:</label><span class="if-error">[[!+fi.error.if-phone]]</span>
    <input type="text" id="if-phone" name="if-phone"/>
  </div>
  <div>
    <label for="if-address">Address:</label>
    <input type="text" id="if-address" name="if-address"/>
  </div>
  <div>
    <label for="if-city">City, State, Zip:</label>
    <input type="text" id="if-city" name="if-city"/>
  </div>

  <div>
    <label for="if-program">Program:</label>
    <select id="if-program" name="if-program">
      <option value="Music Pups" rel="none">Music Pups</option>
      <option value="Young Musicians" rel="none">Young Musicians</option>
      <option value="Music for Young Children" rel="none">Music for Young Children</option>
      <option value="Private lessons" rel="which-instrument">Private music lessons</option>
      <option value="Dance classes" rel="which-class">Dance classes</option>
      <option value="Gymnastics" rel="none">Gymnastics</option>
      <option value="Musical theatre" rel="none">Musical theatre</option>
      <option value="Acting classes" rel="none">Acting classes</option>
    </select>
  </div>
  <div id="if-which-instrument">
    <label for="if-instrument">Instrument:</label>
    <input type="text" id="if-instrument" name="if-instrument"/>
  </div>
  <div id="if-which-class">
    <label for="if-type">Type:</label>
    <select id="if-type" name="if-type">
      <option value="Pre-school" rel="none">Pre-School</option>
      <option value="Ballet" rel="none">Ballet</option>
      <option value="Jazz" rel="none">Jazz</option>
      <option value="Tap" rel="none">Tap</option>
      <option value="Hip Hop" rel="none">Hip Hop</option>
      <option value="Tumble" rel="none">Tumbling</option>
      <option value="Irish" rel="none">Irish Step</option>
      <option value="Bollywood" rel="none">Bollywood</option>
      <option value="Musical Theatre" rel="none">Musical Theatre</option>
      <option value="Latin/Salsa" rel="none">Latin/Salsa</option>
      <option value="Competitive" rel="none">Competitive/team</option>
    </select>
    <label for="if-age">Student's Age:</label>
    <input type="text" id="if-age" name="if-age">
    <input type="hidden" name="workemail" value="">
  </div>
  <div>
    <input type="submit" class="button" id="if-submit" name="if-submit" value="Submit"/>
  </div>
            
</form>

[[!AjaxForm?
  &form=`inquiry-form`
  &snippet=`FormIt`
  &submitVar=`if-submit`
  &hooks=`spam,if-custom,email`
  &emailTpl=`inquiry-form-report`
  &emailSubject=`Site inquiry regarding [[+if-program]]`
  &emailTo=`s*******l@gmail.com`
  &emailFrom=`no-reply@******.com`
  &successMessage =`<strong>Thanks for your inquiry!</strong><br>We will respond to you shortly.`
  &validate=`workemail:blank,
    if-name:required:minLength=^3^,
    if-email:email:required`
]]
```

**Comment by bezumkin** [comment]
AjaxForm is just a wrapper for other snippets.

Try to check how FormIt works without it.

**Comment by bschwenk** [comment]
I understand that.  However, the issue *only* occurs when I wrap with AjaxForm.  When I use the regular FormIt snippet call with exactly the same params, everything works well.

You don't have to pursue this if you don't have enough info or suspect something else as the cause.  I was actually getting ready to abandon FormIt completely and code my own solution before I stumbled upon AjaxForm and figured I'd try one last time to see if I could make FormIt work for my purposes. But I don't think I'm going to be able to.

**Comment by bezumkin** [comment]
On your screenshots memory leak is in the xPDO and MODX classes - not in AjaxForm.

I think, there can be some specific bug with a hook, called via AjaxForm and FormIt. Try to disable them one by one and see what happening.

**Comment by bschwenk** [comment]
No dice. However, I did find the cause.  When I remove this from the AjaxForm snippet call:

`&form='inquiry-form'`

...then the error disappears.

**Comment by bschwenk** [comment]
But the problem with removing that parameter is that if I don't specify the form, it looks like AjaxForm tries to create its own form directly beneath mine.

**Comment by bezumkin** [comment]
OMG, I just understand, that you don`t read description of parameter &form of snippet.
> Chunk with form for submit.

You need to put your form from page to chunk and specify its name in the parameter &chunk.

**Comment by bschwenk** [comment]
It just so happens that my chunk is named the same.  So I was using this parameter correctly, even though I didn't realize it.

![image](https://cloud.githubusercontent.com/assets/8420188/8342993/f5a84720-1a9e-11e5-911a-1702dc9933ee.png)

**Comment by bezumkin** [comment]
Maybe you need to remove inline form from your page as displayed in the first post?

I don`t know how to help you. For all time this is the first kind of such question about AjaxForm.

**Comment by bschwenk** [comment]
Well, there is a first report for every bug ;-) Not to say this is necessarily a bug in AjaxForm; perhaps it is in MODx since it's being triggered in system files.

It's okay. I've found a different solution that does not use FormIt. I understand if you just want to close this issue.

**Comment by bezumkin** [comment]
I think it's some obscure feature or FormIt or its hooks.

In my cases I don`t see any problems.
