### ISSUE TITLE
Uncaught TypeError: Cannot read property 'defaults' of undefined

### ISSUE THREAD

**Issue by Dimension777** [bezumkin/AjaxForm#21]
I use this form on my site, everything like in manual, Email`s are sending but there is no popup window!

Uncaught TypeError: Cannot read property 'defaults' of undefined 
default.js:12
And there is line: 
		$(document).ready(function() {
			$.jGrowl.defaults.closerTemplate = '<div>[ '+afConfig.closeMessage+' ]</div>';
		});
 
I tryed to change jquery, but the popup window still don`t appears.
Help
My website URL is dev2.flamingo-svet.ru

**Comment by bezumkin** [comment]
Ну раз уж на сайте используется jQuery вместо $, то и скрипт нужно переписать на
```
jQuery.jGrowl.defaults
```
и далее по тексту

[![](https://file.modx.pro/files/f/4/4/f448f1fa2377c15203e5fa5f5e4a5ffes.jpg)](https://file.modx.pro/files/f/4/4/f448f1fa2377c15203e5fa5f5e4a5ffe.png)
Наглядно показываю, что $.jGrowl нет, а jQuery.jGrowl - есть.

**Comment by Dimension777** [comment]
Решил данную проблему написав в файл assets/components/ajaxform/js/default.js
$ = jQuery.noConflict();
первой строкой.
Также помог материал на тему конфликтов Jquery
http://modx-shopkeeper.ru/forum/viewtopic.php?id=1290
