### ISSUE TITLE
Disabled input field is enabled after form is submitted

### ISSUE THREAD

**Issue by akommar** [bezumkin/AjaxForm#22]
Hi,

I have a disabled field in the form. After form submission the field becomes enabled. Any idea how I can prevent it from happening?

В форме есть одно поле disabled. После того, как форма либо успешно отсылается, либо валидация «падает», это поле становится доступным для ввода текста. Баг или я что-то не верно сконфигурировал?

**Comment by bezumkin** [comment]
[See this](https://github.com/bezumkin/AjaxForm/blob/7149992e0e2978e1e518ac444f8eae056b03b1f5/assets/components/ajaxform/js/default.js#L42).

**Comment by akommar** [comment]
Thank you. In other words, on submit all fields are forcibly enabled after submit succeeds. Is it a good solution to comment out this line? What would be the reason to make all of them enabled? In my vision what was disabled should stay such, don't you think so?

Спасибо, другими словами все поля принудительно доступны для редактирования после submit. А в чем причина? Не было бы вернее оставить состояние полей? Зачем все их делать enabled? Не понимаю, это все же баг или фича?

**Comment by bezumkin** [comment]
It is because all fields are diabled on submit and then enabled back.

I don`t know why you need to keep disabled fields in form, but you can change javascript as you want.

**Comment by akommar** [comment]
No, it wouldn't be correct to simply comment this line, I see now. Other fields may stay disabled...

Неверно закомментировать эту строку, теперь я вижу. Останутся нужные поля недоступными.

**Comment by akommar** [comment]
Thank you.

Спасибо.
