### ISSUE TITLE
Are two Ajaxforms allowed on the same page?

### ISSUE THREAD

**Issue by jcamachott** [bezumkin/AjaxForm#23]

**Comment by bezumkin** [comment]
Yes

**Comment by jcamachott** [comment]
I have two Ajaxform calls on the same page:

Call 1

    [[!AjaxForm?
    &form=`gettourform-popup`
    &snippet=`FormIt`
    &hooks=`spam,addresstohook,email,FormItSaveForm,FormItAutoResponder,crmhook`
    &formSelector=`gettourform-popup`
    &emailTo=`[[+addressTo]],john@XXX.com`
    &emailSubject=`GET A TOUR FORM: [[+first-name2]] [[+last-name2]]`
    &emailFromName=`COWORK|RS`
    &emailTpl=`email-popup`
    &validate=`first-name2:required,e-mail2:required,interestedin:required,last-name2:required,company-name2:required,phone2:required`
    &validationErrorMessage=`<div class="err_message">Please make sure<br/>All required fields are<br/>filled out correctly</div><div class="err_button"><span>OK</span></div>`
    &successMessage=`<div class="success_head">Thank you</div><div class="success_mesage">for your message<br/>we will contact you soon</div>`
    &fiarTpl=`email-autoresponse-popup`
    &fiarSubject=`Thank you for contacting COWORK|RS!`
    &fiarToField=`e-mail2`
    &fiarFrom=`join@XXX.rs`
    &fiarFromName=`COWORK|RS`
    &fsFormTopic=`bookatour-mainpage`
    &submitVar=`gettourform-popup-submit`
    &formName=`gettourform-popup`
    &store=`1`
    ]]

Call 2

[[!AjaxForm?
      &form=`gettourform`
      &snippet=`FormIt`
      &hooks=`spam,addresstohook,email,FormItSaveForm,FormItAutoResponder,crmhook`
      &formSelector=`gettourform`
      &emailTo=`[[+addressTo]],john@XXXX.com`
      &emailSubject=`GET A TOUR FORM: [[+first-name]] [[+last-name]]`
      &emailFromName=`COWORK|RS`
      &emailTpl=`email`
      &validate=`first-name:required,e-mail:required,interestedin:required,last-name:required,company-name:required,phone:required`
      &validationErrorMessage=`<div class="err_message">Please make sure<br/>All required fields are<br/>filled out correctly</div><div class="err_button"><span>OK</span></div>`
      &successMessage=`<div class="success_head">Thank you</div><div class="success_mesage">for your message<br/>we will contact you soon</div>`
      &fiarTpl=`email-autoresponse`
      &fiarSubject=`Thank you for contacting COWORK|RS!`
      &fiarToField=`e-mail`
      &fiarFrom=`join@XXXX.rs`
      &fiarFromName=`COWORK|RS`
      &fsFormTopic=`bookatour`
      &formName=`gettourform`
      &submitVar=`gettourform-submit`
      &store=`1`

      ]]


Call 1 works fine. Call 2 does not work at all. When I click submit, I get a success message but it bypasses all validation and no email is sent and nothing is recorded in the FormIt data table. Triple checked my submitVars and they are correct on both forms. 

My next step would be to remove the Ajaxform from the form that is not working but hopefully I can get a reply back soon, before I do that.

**Comment by jcamachott** [comment]
So I removed the Ajaxform call on the form that was not working (used plain FormIt call) and got this error upon submitting:  

    Key of form not set (action). 

I google that and it seems to come from Ajaxform, no? 

The problem is I still had class="gettourform" in my form tag, but how/why did AjaxForm still notice it and try to process it? My other ajaxform call had 

    &formName=`gettourform-popup`

and the other form already had

    class="gettourform-popup"

Anyway I removed the class=gettourform from the first form and everything works fine. 

So definitely, something is off with using Ajaxform twice on the same page.

**Comment by bezumkin** [comment]
I will try to find out what the deal and fix it in the near future.

**Comment by jcamachott** [comment]
Thanks!

**Comment by bezumkin** [comment]
Okay, i checked this and don`t see any errors.  Here is my test case:
```
<div class="row">
    <div class="col-md-6">
        [[!AjaxForm?
        	&hooks=`email,FormItSaveForm`
        	&emailTo=`myemail@ya.ru`
        	&emailSubject=`Form 1`
        	&validate=`email:required:email`
        ]]
    </div>
    <div class="col-md-6">
        [[!AjaxForm?
        	&hooks=`email,FormItSaveForm`
        	&emailTo=`myemail@ya.ru`
        	&emailSubject=`Form 2`
        	&validate=`email:required:email`
        ]]
    </div>
</div>
```
Both forms are works.

You can check it yourself at [my test site](http://s2819.h4.modhost.pro/):
```
Manager:  http://s2819.h4.modhost.pro/manager/
User:     s2819
Pass:     FU40k7NSoMJI
```

**Comment by bezumkin** [comment]
Can I close it?

**Comment by jcamachott** [comment]
Well I guess you can close it. I haven't had the time to check it, but I just went into your link and it seems to be broken now. But in my forms I was using &formSelector and changed the class for both forms. Close the issue. If I encounter again I will try to do a proper explanation.

**Comment by bezumkin** [comment]
> but I just went into your link and it seems to be broken now

Yes, it was free test site for 24 hours.
