### ISSUE TITLE
Обработка reCapcha

### ISSUE THREAD

**Issue by vashot** [bezumkin/AjaxForm#24]
/* Дополнение для "public function handleFormIt", строка 153 */
/* Обработка reCapcha v1 (FormIt) */
if(!empty($this->modx->placeholders[$plPrefix.'error.recaptcha'])) {
   $errors['recaptcha'] = $this->modx->placeholders[$plPrefix.'error.recaptcha'];
}

/* Обработка reCapcha v2 (FormIt+ReCaptchaV2) */
if(!empty($this->modx->placeholders[$plPrefix.'error.recaptchav2_error'])) {
   $errors['recaptcha'] = $this->modx->placeholders[$plPrefix.'error.recaptchav2_error'];
}

**Comment by bezumkin** [comment]
Предлагаю оформить нормальный pull-request через [редактирование нужного файла](https://help.github.com/articles/editing-files-in-another-user-s-repository/).

**Comment by bezumkin** [comment]
https://github.com/bezumkin/AjaxForm/pull/25
