### ISSUE TITLE
Форма в модальном окне

### ISSUE THREAD

**Issue by Germiningeld** [bezumkin/AjaxForm#29]
Василий, добрый день.
Спасибо за AjaxForm, очень упрощает жизнь.
Сейчас возник вопрос. Вывожу форму в модальном окне (bootstrap) и после удачной отправки очень хочется скрыть окно (сейчас приходится закрывать руками).
Подскажите пожалуйста что для этого можно сделать (скрипт для закрытия модали в bootstrap $('#myModal').modal({show: false}) - но не знаю куда его воткнуть)

**Comment by bezumkin** [comment]
```
$(document).on('af_complete', function(e, res) {
    if (res.success) {
        $('#myModal').modal({show: false})
    }
})
```

**Comment by Germiningeld** [comment]
Василий, спасибо

31.03.2016 8:41, Vasily Naumkin пишет:
